import { execSync } from "node:child_process";
import path from "node:path";
import fs from "node:fs";
import { fileURLToPath } from "node:url";
import dotenv from "dotenv";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Load E2E env vars
dotenv.config({ path: path.resolve(__dirname, ".env.e2e") });

const DATABASE_URL =
  process.env["DATABASE_URL"] ??
  "postgresql://kanon:kanon@localhost:5432/kanon_e2e?schema=public";

const API_PKG_DIR = path.resolve(__dirname, "../api");

export default async function globalSetup(): Promise<void> {
  console.log("\n[e2e] Global setup starting...");
  console.log(`[e2e] DATABASE_URL: ${DATABASE_URL.replace(/\/\/.*@/, "//***@")}`);

  // Step 1: Reset and seed the test database using Prisma
  // The PRISMA_USER_CONSENT env var is required because Prisma detects AI agents
  // and blocks destructive operations. This is safe: we target the kanon_e2e test DB.
  const prismaEnv = {
    ...process.env,
    DATABASE_URL,
    PRISMA_USER_CONSENT_FOR_DANGEROUS_AI_ACTION: "yes",
  };

  console.log("[e2e] Running prisma migrate reset --force...");
  execSync("npx prisma migrate reset --force --skip-generate", {
    cwd: API_PKG_DIR,
    env: prismaEnv,
    stdio: "pipe",
  });

  console.log("[e2e] Running prisma db seed...");
  execSync("npx prisma db seed", {
    cwd: API_PKG_DIR,
    env: prismaEnv,
    stdio: "pipe",
  });

  // Step 2: Query the workspace UUID from the seeded database
  // Write a temp script to avoid shell escaping issues with inline code
  console.log("[e2e] Resolving seed data constants...");
  // Write the temp script into the API package dir so @prisma/client resolves correctly
  const tmpScript = path.resolve(API_PKG_DIR, ".tmp-resolve-workspace.mjs");
  fs.writeFileSync(
    tmpScript,
    [
      `import { PrismaClient } from '@prisma/client';`,
      `const prisma = new PrismaClient();`,
      `try {`,
      `  const w = await prisma.workspace.findFirst({ where: { slug: 'kanon-dev' } });`,
      `  console.log(JSON.stringify(w));`,
      `} finally {`,
      `  await prisma.$disconnect();`,
      `}`,
    ].join("\n"),
    "utf-8",
  );

  try {
    const result = execSync(`npx tsx ${tmpScript}`, {
      cwd: API_PKG_DIR,
      env: { ...process.env, DATABASE_URL },
      stdio: ["pipe", "pipe", "pipe"],
    });

    const workspace = JSON.parse(result.toString().trim()) as {
      id: string;
      slug: string;
      name: string;
    };

    // Write seed constants to a file that test helpers can import
    const envTestPath = path.resolve(__dirname, ".env.test");
    const envContent = [
      `# Auto-generated by global-setup.ts -- do not edit`,
      `SEED_WORKSPACE_ID=${workspace.id}`,
      `SEED_WORKSPACE_SLUG=${workspace.slug}`,
      `SEED_USER_EMAIL=dev@kanon.io`,
      `SEED_USER_PASSWORD=Password1!`,
      "",
    ].join("\n");

    fs.writeFileSync(envTestPath, envContent, "utf-8");
    console.log(`[e2e] Wrote seed constants to ${envTestPath}`);
    console.log(`[e2e] Workspace ID: ${workspace.id}`);
  } finally {
    // Clean up temp script
    if (fs.existsSync(tmpScript)) {
      fs.unlinkSync(tmpScript);
    }
  }

  console.log("[e2e] Global setup complete.\n");
}
